###############################################
#!/bin/bash

#PBS -o cluster/test.out
#PBS -e cluster/test.err
#PBS -l nodes=1:ppn=24
#PBS -l walltime=10000:00:00

export PATH=/home/data/anaconda3/bin:$PATH

#
# o Export all my environment variables to the job
#PBS -V
#

source ~/.bashrc

cd /home/users/ajarekar/master-thesis-quantumkernelclassification

if [ $(conda activate kgreedy; echo $?) -eq 1 ]; then conda env create -f environment.yml; fi
conda activate kgreedy


python test.py 

# o qsub -q iisb -m "abe" -M "digvijaysinh.ajarekar@iisb.fraunhofer.de" cluster/test.job
